# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
#before:
  #hooks:
    # you may remove this if you don't use vgo
    # - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
before:
  hooks:
  - make npm-install
  - make fe
builds:
  -
    env:
    - CGO_ENABLED=0
    id: "brontosaurus-ponderosa"
    binary: "brontosaurus-ponderosa"
    main: ./go/src/bp/main.go
    hooks:
      post: du -a && alksjdas #make bintarget=dist/brontosaurus-ponderosa_darwin_amd64/brontosaurus-ponderosa sign
  -
    env:
    - CGO_ENABLED=0
    id: "ponderosa-brontosaurus"
    binary: "ponderosa-brontosaurus"
    main: ./go/src/pb/main.go
    hooks:
      post: make bintarget=dist/brontosaurus-ponderosa_darwin_amd64/ponderosa-brontosaurus sign

archives:
  -
    files:
    - fe/dist/**/*
    builds:
    - "brontosaurus-ponderosa"
    - "ponderosa-brontosaurus" 

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: trevorfsmith
    name: brontosaurus-ponderosa
