name: Build and release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: macOS-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Set up go
        uses: actions/setup-go@master
      -
        name: Set ENVs
        run: |
          echo "##[set-env name=GIT_TAG;]echo $GITHUB_REF | cut -d"/" -f3
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)/brontosaurus-ponderosa/go"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/brontosaurus-ponderosa/go/bin"
        shell: bash
      -
        name: Show ENVs
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GIT_TAG: $GIT_TAG"
          echo "GOPATH: $GOPATH"
        shell: bash
      -
        name: Build and release
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.ReleaseToken }}
      -
        name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NpmAuthToken }}" > ~/.npmrc
          git config --global user.email "trevor@trevor.smith.name"
          git config --global user.name "trevorfsmith"
          cd package
          npm publish
  build-github-docker-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: trevorfsmith/brontosaurus-ponderosa/brontosaurus-ponderosa
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
