name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Set up Go
        uses: actions/setup-go@master
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.ReleaseToken }}
      -
        name: NPM Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NpmAuthToken }}" > ~/.npmrc
          git config --global user.email "trevor@trevor.smith.name"
          git config --global user.name "trevorfsmith"
          cd package
          npm publish

